### ISSUE TITLE
"Duplicate and Missing Cases": link to Web Archive?

### ISSUE THREAD

**Issue by aitap** [lindbrook/cholera#494]
Hello,

There is a link in the  `duplicate.missing.cases`  vignette that no longer works. Perhaps you may find it useful to replace the link to https://www.ncgia.ucsb.edu/pubs/snow/snow.html (it 404s for me at least) with a Web Archive link to https://web.archive.org/web/20100703135709/http://ncgia.ucsb.edu/Publications/Software/cholera/ (with working links to the original digitised data and even BASIC source code for the map program).

**Comment by lindbrook** [comment]
Thanks! The original URL hasn't worked in a long time. #495

**Comment by lindbrook** [comment]
#496 too.

**Comment by aitap** [comment]
Thank you for fixing the links!
